name = "Ahbah Travel And Tours Theme"
license = "MIT"
licenselink = "https://github.com/0sama-Mirza/ahbab-travels-tours-theme/LICENSE"
description = "A theme for a travel agency"
homepage = "https://github.com/0sama-Mirza/ahbab-travels-tours-theme"
tags = ["conference", "DevFest", "ahbab", "travel"]
features =  ["conference", "responsive", "l10n", "google-analytics"]
min_version = "0.50"

[author]
  name = "0sama"
  homepage = "//github.com/0sama-Mirza"
